
return {
   EUR = "Europe euro",
   USD = "US dollar",
   JPY = "Japanese yen",
   BGN = "Bulgarian lev",
   CZK = "Czech koruna",
   DKK = "Danish krone",
   GBP = "Pound sterling",
   HUF = "Hungarian forint",
   PLN = "Polish zloty",
   RON = "Romanian leu",
   SEK = "Swedish krona",
   CHF = "Swiss franc",
   NOK = "Norwegian krone",
   HRK = "Croatian kuna",
   RUB = "Russian rouble",
   TRY = "Turkish lira",
   AUD = "Australian dollar",
   BRL = "Brazilian real",
   CAD = "Canadian dollar",
   CNY = "Chinese yuan",
   HKD = "Hong Kong dollar",
   IDR = "Indonesian rupiah",
   ILS = "Israeli shekel",
   INR = "Indian rupee",
   KRW = "South Korean won",
   MXN = "Mexican peso",
   MYR = "Malaysian ringgit",
   NZD = "New Zealand dollar",
   PHP = "Philippine peso",
   SGD = "Singapore dollar",
   THB = "Thai baht",
   ZAR = "South African rand"
}

